[workspace]
members = [
  "learning/magazine-cutout",
  "learning/assembly-line",
  "learning/semi-structured-logs",
  "learning/resistor-color",
  "learning/health-statistics",
  "learning/role-playing-game",
]
